# This is a basic workflow to help you get started with Actions

name: Test PR

# Controls when the action will run. 
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Env
        run: export JAVA_HOME="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home"
        run: export

      # Builds
      - name: Builds
        run: ./gradlew test
